export enum ServiceType {
  BATH = 'BATH',
  HAIRCUT = 'HAIRCUT',
  CONSULTATION = 'CONSULTATION',
  FOLLOWUP = 'FOLLOW UP',
  DAYCARE = 'DAYCARE',
  TRANSPORTATION = 'PET TRANSPORTATION',
  MEDICALREVIEW = 'MEDICAL REVIEW',
}
